project:
  type: book
  output-dir: ../docs

book:
  title: "Structural Equation Modeling with Onyx"
  author: "Andreas Brandmaier"
  date: "16.4.2026"
  chapters:
    - index.qmd
    - intro.qmd
    - installation.qmd
    - basics.qmd
    - loaddata.qmd
    - modelfit.qmd
    - multigroup.qmd
    - modelcomparison.qmd
    - factorscores.qmd
    - export.qmd
    - simulation.qmd
    - exercises.qmd
    - exercise-memory.qmd
    - exercise-braincognition.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

website: 
  title: X
  navbar: 
    left: 
      - href: index.qmd
      - text: Home
      - about.qmd

format:
  html:
    toc: true
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
#  outputdir: _site



